name: Mayank

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "client/pnpm-lock.yaml"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./client

      - name: Build
        run: pnpm run build
        working-directory: ./client

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build-artifact
          path: client/dist/
          if-no-files-found: warn
          retention-days: 1

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "client/pnpm-lock.yaml"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./client

      - name: Run Unit Tests
        run: pnpm test
        working-directory: ./client

  server-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "server/pnpm-lock.yaml"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./server

      - name: Verify Server
        run: pnpm run build
        working-directory: ./server

  server-tests:
    runs-on: ubuntu-latest
    needs: server-build
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "server/pnpm-lock.yaml"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./server

      - name: Run Server Tests
        run: pnpm test
        working-directory: ./server
