name: Mayank

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build-artifact
          path: client/dist/
          if-no-files-found: warn
          retention-days: 1

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ./client

      - name: Run Unit Tests
        run: npm test
        working-directory: ./client

  server-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ./server

      - name: Verify Server
        run: npm run build
        working-directory: ./server

  server-tests:
    runs-on: ubuntu-latest
    needs: server-build
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ./server

      - name: Run Server Tests
        run: npm test
        working-directory: ./server
